services:
  postgres:
    image: postgres:14
    container_name: ${PROJECT_NAME}-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PROJECT_NAME}-pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "pgadmin_data:/var/lib/pgadmin:rw"
    ports:
      - "${PGADMIN_PORT}:80"
  dataingest:
    image: mm:v1
    container_name: ${PROJECT_NAME}-dataingest
    env_file:
      - .env
    build:
      context: ./python_ingestion
      dockerfile: Dockerfile
    environment:
      - user=${POSTGRES_USER}
      - password=${POSTGRES_PASSWORD}
      - host=${POSTGRES_HOST}
      - port=${POSTGRES_PORT}
      - db=${POSTGRES_DB}
      - tables=${POSTGRES_TABLES}
    volumes:
      - "./data:/app/data:rw"
    depends_on:
      - postgres
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: ./mage_orchestration
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - "mage_data:/home/src/"
    ports:
      - ${MAGE_PORT}:6789
    restart: on-failure:5
volumes:
    postgres_data:
    pgadmin_data:
    mage_data: