version: "3"
services:
  magic:
    image: mageai/mageai:latest
    container_name: ${PROJECT_NAME}-magic
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: ./mage_orchestration
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - "mage_data:/home/src/"
      - "/home/${HOME_USER}/.gc/mage.json:/home/src/mage.json"
      - "/home/${HOME_USER}/.kaggle/kaggle.json:/.kaggle/kaggle.json"
    ports:
      - ${MAGE_PORT}:6789
    restart: on-failure:5
  metabase:
    image: metabase/metabase:latest
    container_name: ${PROJECT_NAME}-metabase
    env_file:
      - .env
    environment:
      MB_DB_FILE: ${METABASE_DB}
    volumes:
      - "metabase_data:/metabase-data"
    ports:
      - ${METABASE_PORT}:3000
volumes:
    mage_data:
    metabase_data: